# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
