# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170710_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='title',
            new_name='slug',
        ),
    ]
